services:
  laravel-server:
    image: riyadmurad44/laravel_amp_intelligence:latest
    environment:
      - LARAVEL_DATABASE_HOST=placeholder
      - LARAVEL_DATABASE_NAME=placeholder
      - LARAVEL_DATABASE_USER=placeholder
      - LARAVEL_DATABASE_PASSWORD=placeholder
      - LARAVEL_DATABASE_PORT_NUMBER=placeholder
    ports:
      - 8000:80
    depends_on:
      - mysql-database
    restart: always
    command: ./dockerShell.sh
    mem_limit: 300m
    cpus: 0.35

  mysql-database:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: placeholder
      MYSQL_DATABASE: placeholder
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-lowmem.cnf:/etc/mysql/conf.d/custom.cnf
    mem_limit: 400m
    cpus: 0.40
    
      

  node-server:
    image: riyadmurad44/node_amp_intelligence:latest
    ports:
      - 3001:3001
    restart: always
    environment:
      - NODE_OPTIONS=--max-old-space-size=128
    mem_limit: 150m
    cpus: 0.25

volumes:
  mysql-data:
