services:
  laravel-server:
    image: riyadmurad44/laravel_amp_intelligence:latest
    environment:
      - LARAVEL_DATABASE_HOST=placeholder
      - LARAVEL_DATABASE_NAME=placeholder
      - LARAVEL_DATABASE_USER=placeholder
      - LARAVEL_DATABASE_PASSWORD=placeholder
      - LARAVEL_DATABASE_PORT_NUMBER=placeholder
    ports:
      - 8000:80
    depends_on:
      - mysql-database
    restart: always
    command: ./dockerShell.sh

  mysql-database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: placeholder
      MYSQL_DATABASE: placeholder
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  node-server:
    image: riyadmurad44/node_amp_intelligence:latest
    ports:
      - 3001:3001
    restart: always

volumes:
  mysql-data:
