name: Push Laravel, React and Node.js Images To DockerHub Then Deploy to EC2 Staging

on:
  push:
    branches:
      - staging

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Inject GitHub Secrets into .env.example
      working-directory: amp-laravel
      run: |
        echo "APP_KEY=${{ secrets.LARAVEL_APP_KEY }}" > .env.example
        echo "DB_CONNECTION=mysql" >> .env.example
        echo "DB_HOST=${{ secrets.LARAVEL_DATABASE_HOST }}" >> .env.example
        echo "DB_PORT=${{ secrets.LARAVEL_DATABASE_PORT_NUMBER }}" >> .env.example
        echo "DB_DATABASE=${{ secrets.LARAVEL_DATABASE_NAME }}" >> .env.example
        echo "DB_USERNAME=${{ secrets.LARAVEL_DATABASE_USER }}" >> .env.example
        echo "DB_PASSWORD=${{ secrets.LARAVEL_DATABASE_PASSWORD }}" >> .env.example
        echo "JWT_SECRET=${{ secrets.LARAVEL_JWT_SECRET }}" >> .env.example
        echo "JWT_ALGO=HS256" >> .env.example
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.example

    - name: Build Laravel Docker image
      working-directory: amp-laravel
      run: docker build -f Dockerfile-Laravel -t ${{ secrets.DOCKER_USERNAME }}/laravel_amp_intelligence:latest .

    - name: Push Laravel Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel_amp_intelligence:latest

  Build-NodeJS-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Node.js Docker image
        working-directory: amp-node
        run: docker build -f Dockerfile-Node -t ${{ secrets.DOCKER_USERNAME }}/node_amp_intelligence:latest .

      - name: Push Node.js Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node_amp_intelligence:latest

  Build-ReactJS-And-Deploy-On-S3-Bucket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Check Node.js version
        run: node -v

      - name: Check npm version
        run: npm -v

      - name: Inject GitHub Secrets into .env.production
        working-directory: ./amp-client
        run: sed -i "s|VITE_API_BASE_URL=.*|VITE_API_BASE_URL=http://${{ secrets.EC2_HOST_STAGING }}:8000|g" .env.production
                  
      - name: Copy .env.production to .env
        working-directory: ./amp-client
        run: cp .env.production .env

      - name: Install dependencies
        working-directory: ./amp-client
        run: npm install

      - name: Build React Project
        working-directory: ./amp-client
        run: npm run build

      - name: Copy dist file to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "amp-client/dist"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Deploy on S3 bucket
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "[default]" > ~/.aws/config
            echo "region = ${{ secrets.AWS_DEFAULT_REGION }}" >> ~/.aws/config
            aws s3 cp amp-client/dist/ s3://fse-final-riyad --recursive --no-sign-request

  Copy-docker-compose-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Inject GitHub Secrets into docker-compose.yaml
        run: |
          sed -i "s|LARAVEL_DATABASE_HOST=.*|LARAVEL_DATABASE_HOST=${{ secrets.LARAVEL_DATABASE_HOST }}|g" docker-compose.yaml
          sed -i "s|LARAVEL_DATABASE_NAME=.*|LARAVEL_DATABASE_NAME=${{ secrets.LARAVEL_DATABASE_NAME }}|g" docker-compose.yaml
          sed -i "s|LARAVEL_DATABASE_USER=.*|LARAVEL_DATABASE_USER=${{ secrets.LARAVEL_DATABASE_USER }}|g" docker-compose.yaml
          sed -i "s|LARAVEL_DATABASE_PASSWORD=.*|LARAVEL_DATABASE_PASSWORD=${{ secrets.LARAVEL_DATABASE_PASSWORD }}|g" docker-compose.yaml
          sed -i "s|LARAVEL_DATABASE_PORT_NUMBER=.*|LARAVEL_DATABASE_PORT_NUMBER=${{ secrets.LARAVEL_DATABASE_PORT_NUMBER }}|g" docker-compose.yaml
          sed -i "s|MYSQL_ROOT_PASSWORD:.*|MYSQL_ROOT_PASSWORD: ${{ secrets.LARAVEL_DATABASE_PASSWORD }}|g" docker-compose.yaml
          sed -i "s|MYSQL_DATABASE:.*|MYSQL_DATABASE: ${{ secrets.LARAVEL_DATABASE_NAME }}|g" docker-compose.yaml

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/"

  Deploy-To-EC2:
    needs:
      [
        Build-Laravel-And-Push-Dockerhub,
        Build-NodeJS-And-Push-Dockerhub,
        Build-ReactJS-And-Deploy-On-S3-Bucket,
        Copy-docker-compose-To-EC2,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/laravel_amp_intelligence:latest
            docker rmi ${{ secrets.DOCKER_USERNAME }}/node_amp_intelligence:latest            
            docker compose up -d
