name: Run Laravel Tests for Production

on:
  pull_request:
    branches:
      - main

jobs:
  Laravel_Tests_Production:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Laravel Docker image
        working-directory: ./amp-laravel
        run: docker build -f Dockerfile-Laravel -t laravel_test_image .

      - name: Run Laravel Tests inside Docker
        working-directory: ./amp-laravel
        run: |
          docker run --rm \
            --network="host" \
            -e APP_ENV=testing \
            -e DB_CONNECTION=mysql \
            -e DB_HOST=127.0.0.1 \
            -e DB_PORT=3306 \
            -e DB_DATABASE=testing \
            -e DB_USERNAME=root \
            -e DB_PASSWORD=root \
            -e CACHE_DRIVER=array \
            -e SESSION_DRIVER=array \
            -e QUEUE_CONNECTION=sync \
            --entrypoint "" \
            laravel_test_image \
            sh -c "cp .env.testing .env && composer install && php artisan config:clear && php artisan key:generate && php artisan jwt:secret --force && php artisan migrate && php artisan test"

