name: Run Laravel Tests for Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  Laravel_Tests_Staging:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Laravel Docker image
        working-directory: ./amp-laravel
        run: |
          docker build -f Dockerfile-Laravel -t laravel_test_image .

      - name: Run Laravel Tests inside Docker
        working-directory: ./amp-laravel
        run: |
          docker run --rm \
            --network="host" \
            -e APP_ENV=testing \
            -e DB_CONNECTION=mysql \
            -e LARAVEL_DATABASE_HOST=127.0.0.1 \
            -e LARAVEL_DATABASE_PORT_NUMBER=3306 \
            -e LARAVEL_DATABASE_NAME=testing \
            -e LARAVEL_DATABASE_USER=root \
            -e LARAVEL_DATABASE_PASSWORD=root \
            -e CACHE_DRIVER=array \
            -e SESSION_DRIVER=array \
            -e QUEUE_CONNECTION=sync \
            laravel_test_image \
            sh -c "php artisan test"
